project_id = "lmagkjgpnfffqsufycsf"

[functions.voice-parse]
verify_jwt = false

[functions.voice-parse-expense]
verify_jwt = false

[functions.voice-parse-procurement]
verify_jwt = false

[functions.parse-dairy-image]
verify_jwt = false
